const CategoriesList = {
  Menswear: {
    Tops: {
      "T-shirts": "",
      "Long Sleeve T-Shirts": "",
      Polos: "",
      "Button-up Shirts": "",
      Sweaters: "",
      Cardigans: "",
      Sweatshirts: "",
      Hoodies: "",
      Sleeveless: "",
      Jerseys: "",
    },
    Bottoms: {
      Shorts: "",
      Sweatpants: "",
      Joggers: "",
      Overalls: "",
      Denim: "",
      Trousers: "",
      Leggings: "",
    },
    Outerwear: {
      Coats: "",
      Bombers: "",
      Cloaks: "",
      "Denim Jackets": "",
      "Leather Jackets": "",
      Raincoats: "",
      Vests: "",
    },
    Footwear: {
      Sneakers: "",
      Trainers: "",
      Boots: "",
      "Formal Shoes": "",
      Slides: "",
      Sandals: "",
      "Slip-ons": "",
    },
    Tailoring: {},
    Accessories: {
      Bags: "",
      Belts: "",
      Hats: "",
      Gloves: "",
      Scarves: "",
      Sunglasses: "",
      Wallets: "",
      Jewellry: "",
      Watches: "",
    },
  },
  Womenswear: {},
  Kidswear: {},
};

export default CategoriesList;
