import { SIZES } from "./constants";

const data = [
  {
    title: "U Crew Neck Short Sleeve T-Shirt",
    brand: "UNIQLO",
    desc: "Heavyweight fabric gains character the more you wear it. Flattering roomy fit.",
    price: 120,
    size: SIZES.M,
    color: "Dark Purple",
    images: [
      "https://image.uniqlo.com/UQ/ST3/WesternCommon/imagesgoods/422992/item/goods_79_422992.jpg?width=750",
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/422992/sub/cagoods_422992_sub3.jpg?width=750",
    ],
    sellerID: "0",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
  {
    title: "Sweat Pullover Hoodie",
    brand: "UNIQLO",
    desc: "Fine sweat fabric with lovely color. Perfectly thick for easy layering.",
    price: 40,
    size: SIZES.L,
    color: "Pink",
    images: [
      "https://image.uniqlo.com/UQ/ST3/ca/imagesgoods/444967/item/cagoods_12_444967.jpg?width=750",
    ],
    sellerID: "1",
    datePosted: new Date(),
  },
];

export { data };
